  baseURL: "https://krishnatejaj.github.io"
  languageCode: "en-us"
  title: "Krishna Teja Jillelamudi"
  theme: hugo-profile

  outputs:
    home:
      - "HTML"
      - "RSS"
      - "JSON"
    page:
      - "HTML"
      - "RSS"

  Paginate: 3
  enableRobotsTXT: true
  # disqusShortname: your-disqus-shortname
  # googleAnalytics: G-MEASUREMENT_ID

  markup:
    goldmark:
      renderer:
        unsafe: true

  Menus:
    main:
      - identifier: blog
        name: Blog
        title: Blog posts
        url: /blogs
        weight: 1
      - identifier: gallery
        name: Gallery
        title: Blog posts
        url: /gallery
        weight: 2
      #Dropdown menu
      # - identifier: dropdown
      #   title: Example dropdown menu
      #   name: Dropdown
      #   weight: 3
      # - identifier: dropdown1
      #   title: example dropdown 1
      #   name: example 1
      #   url: /#
      #   parent: dropdown
      #   weight: 1
      # - identifier: dropdown2
      #   title: example dropdown 2
      #   name: example 2
      #   url: /#
      #   parent: dropdown
      #   weight: 2

  params:
    #title: "Krishna Teja Jillelamudi"
    #description: Text about my cool site
    # staticPath: ""  # The path to serve the static files from
    #favicon: ""

    # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
    # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
    # Note the lack of "" in true, it should be of boolean type.
    useBootstrapCDN: false

    # If you want to load dynamically responsive images from Cloudinary
    # This requires your images to be uploaded + hosted on Cloudinary
    # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
    # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
    
    # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
    mathjax: false

    # Whether the fade animations on the home page will be enabled
    animate: true

    theme:
      # disableThemeToggle: true
      # defaultTheme: "light" # dark

    font:
      fontSize: 1rem # default: 1rem
      fontWeight: 400 # default: 400
      lineHeight: 1.5 # default: 1.5
      textAlign: left # default: left

    # color preference
    # color:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

    #   darkmode:
    #     textColor:
    #     secondaryTextColor:
    #     backgroundColor:
    #     secondaryBackgroundColor:
    #     primaryColor:
    #     secondaryColor:

    # If you want to customize the menu, you can change it here
    navbar:
      align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
      # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
      # showBrandLogo: false # Show brand logo in nav bar | default is true
      #brandName: "Krishna Teja Jillelamudi" # Brand name for the brand | default is the title variable
      #disableSearch: false
      # searchPlaceholder: "Search"
      stickyNavBar:
        enable : true
        showOnScrollUp : true
      menus:
        disableAbout: false
        disableExperience: false
        disableEducation: false
        disableProjects: false
        disableAchievements: false
        disableContact: false

    # Hero
    hero:
      enable: true
      intro: "Hi, my name is"
      title: "Krishna Teja Jillelamudi."
      #subtitle: "In constant pursuit of uncovering stories through data."
      content: "I am a data explorer working on diverse projects across various domains, driven by the ambition to create a positive impact in the real world."
      image: 836.jpg
      bottomImage:
        enable: true
        roundImage: true # Make hero image circular | default false
      button:
        enable: true
        name: "Resume"
        url: "https://drive.google.com/file/d/1zXT6RdVEog9r7m3q5Wgw7zel2c9o8kA1/view?usp=sharing"
        download: true
        newPage: true
      socialLinks:
        fontAwesomeIcons:
          - icon: fab fa-github
            url: https://github.com/KrishnaTejaJ
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/in/krishna-teja-jillelamudi/
        #customIcons:
          #- icon: /fav.png
            #url: "https://example.com"

    # About
    about:
      enable: true
      title: "About Me"
      #image: "/images/me.png"
      content: |-
        I am a Master's student in Data Science at Indiana University Bloomington. With a background in software development and a passion for artificial intelligence, I'm driven to build data-driven solutions that bring insights and innovation to real-world problems.

        My experience ranges from developing an inclusive AI hiring tool at Omdena to programming healthcare applications at Tata Consultancy Services. I thrive on hands-on projects, having contributed to research on skin lesion analysis and explored techniques like recommendation systems and audio sentiment analysis.

        I'm well-versed in Python and a suite of data science libraries (Pandas, Scikit-learn, Tensorflow, etc.). Outside of my studies, you might find me competing in hackathons or experimenting with data visualization tools.
      skills:
        enable: true
        title: "Here are a few technologies I've been working with recently:"
        items:
          - "Large Language Models (LLMs)"
          - "Tableau"
          - "Google Cloud Platform"
          - "Python"


    # experience
    experience:
      enable: true  
      # title: "Custom Name" # You can uncomment this line and enter a title like "Education" if you'd like
      index: false 
      

    # Education
    education:
      enable: true  
      # title: "Custom Name" # You can uncomment this line and enter a title like "Education" if you'd like
      index: false 
      items:
        - title: "Master of Science, Data Science" 
          school:
            name: "Indiana University Bloomington" 
            url: "https://www.iu.edu/" # Add the Indiana University website  
          date: "August 2022 - May 2024 (Expected)" 
          # GPA: "3.8 out of 4.0"  # Optional - uncomment if you want to include GPA
          content: |-
            Courses: Introduction to Statistics, Elements of AI, Data Mining, Applied ML, Data Science in Practice, Network Science. 
        - title: "Bachelor of Technology, Computer Science and Engineering" 
          school:
            name: "SR Engineering College" 
            url: "https://www.srecwarangal.ac.in/"  # Add SR Engineering College website
          date: "May 2017 - July 2021" 
          # GPA: "3.9 out of 4.0"  # Optional - uncomment if you want to include GPA
          content: |-
            Courses: Artificial intelligence and business systems, Data warehousing and data mining, Grid and cloud computing, Neural networks and deep learning, Big data and analytics.
          #  featuredLink: # No need for featured links with just course lists
          #    enable: true 
          #    name: "My academic record" 
          #    url: "https://example.com" # Add your academic record link here


    # Achievements
    achievements:
      enable: true
      # title: "Custom Name"
      items:
        - title: AIHackathon 2019 Runner-up
          content: Evaluated audio clip conversations between call center employees and customers using NLP to classify sentiments, resulting in an emotion category, and attained second runner-up position in the AIHackathon 2019, hosted by Tata Motors in SIT, Pune.
          url: https://www.linkedin.com/feed/update/urn:li:activity:6586130025911816192/
          image: /project-images/aihackathon19.png
        
        - title: Smart City Warangal Hackathon 2019 Winner
          content: Developed a Virtual Tourist Guide app which uses image recognition to provide information about the historical places in Warangal, and won the Smart City Warangal Hackathon, 2019.
          image: /project-images/vtourist-s.png

    # projects
    projects:
      enable: true
      # title: "Custom Name"
      items:
        - title: Visualizing Civic Engagement - City of Bloomington
          content: The goal of this project is to analyze and visualize civic engagement data for the city of Bloomington, Indiana using the comprehensive Open311 dataset.
          image: /project-images/bubblemap.png
          #featured:
            #name: Demo
            #link: https://hugo-profile.netlify.app
          badges:
            - "Data Visualization"
            - "Python"
            - "Folium"
          links:
            #- icon: fa fa-envelope
              #url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
            - icon: fab fa-github
              url: https://github.com/KrishnaTejaJ/Visualizing-Civic-Engagement-City-of-Bloomington
            #- icon: fab fa-twitter
              #url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

        - title: Exploring Development Funds Flow
          content: A Network analysis project focused on exploring the flow of development funds using Official Development Assistance (ODA) data collected by the Organisation for Economic Co-operation and Development (OECD).
          image: /project-images/page-rank.png
          #featured:
            #name: Demo
            #link: https://django-converter.herokuapp.com
          badges:
            - "Network Science"
            - "Community Detection"
            - "Gephi"
            - "NetworkX"
          links:
            - icon: fab fa-github
              url: https://github.com/KrishnaTejaJ/flow-of-global-economic-aid-funds

        - title: Chronic Heart Disease Prediction
          content: The ML models in the project uses attributes, including medical terms like Sex, Age, Blood Pressure, and Cholesterol, to predict the likelihood that a patient will develop heart disease using BRFSS survey data, which is the most comprehensive collection of state information on U.S. citizens' risk behaviors, chronic health issues, and utilization of preventive care in the country.
          image: /project-images/bmi.png
          #featured:
            #name: Demo V2
            #link: https://hugo-profile-2.netlify.app
          badges:
            - "Machine Learning"
            - "Data Mining"
          links:
            - icon: fab fa-github
              url: https://github.com/KrishnaTejaJ/chronic-heart-disease-prediction
        
        - title: Characterizing Logging in Data Science and Non Data Science Github Repositories
          content: In this work, a quantitive and qualitatively analysis of log statements from GitHub open-source code repositories of Data Science and Non-Data Science (Software Engineering) applications is performed to better understand the logging practices in both fields.
          image: /project-images/python-count-gini.png
          #featured:
            #name: Demo V2
            #link: https://hugo-profile-2.netlify.app
          badges:
            - "Logging"
            - "Semgrep"
            - "GitHub"
          links:
            - icon: fab fa-github
              url: https://github.com/KrishnaTejaJ/logging-inequalities-ds-nds

    #Contact
    contact:
      enable: true
      # title: "Custom Name"
      content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
      email: ktjillelamudi@gmail.com
      btnName: Mail me
      # formspree:
      #   enable: true # `contact.email` value will be ignored
      #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      #   emailCaption: "Enter your email address"
      #   messageCaption: "Enter your message here"

    footer:
      recentPosts:
        path: "blogs"
        count: 3
        title: Recent Posts
        enable: false
        disableFeaturedImage: false
      socialNetworks:
        github: https://github.com/KrishnaTejaJ
        linkedin: https://www.linkedin.com/in/krishna-teja-jillelamudi/

    # List pages like blogs and posts
    listPages:
      disableFeaturedImage: false

    # Single pages like blog and post
    singlePages:
      readTime:
        enable: false
        content: "min read"
      scrollprogress:
        enable: false

    # For translations
    terms:
      read: "Read"
      toc: "Table Of Contents"
      copyright: "All rights reserved"
      pageNotFound: "Page not found"
      emailText: "Check out this site"

    #datesFormat:
      #article: "Jan 2, 2006"
      #articleList: "Jan 2, 2006"
      #articleRecent: "Jan 2, 2006"

    #customScripts: -| # You can add custom scripts which will be added before </body> tag
    #  <script type="text/javascript"><!-- any script here --></script>
